### ISSUE TITLE
Recommend App "Schau dir das mal an..." soll Link zu Squirrel News App Store Page ausgeben

### ISSUE THREAD

**Issue by olierxleben** [ConstructiveNews/squirrel-news-app#140]
"empfiehl uns weiter"

**Comment by constructive-news** [comment]
Ich würde den Text, der zum Link dazugeschrieben wird, wenn man es teilt noch ergänzen: Bisher steht das: "Schau dir das mal an...", Ich würde stattdessen schreiben: "Diese App kann ich nur empfehlen: Squirrel News sammelt die wichtigsten lösungsorientierten Medienbeiträge, alles kostenlos"
