### ISSUE TITLE
Mastodon Link is broken

### ISSUE THREAD

**Issue by olierxleben** [ConstructiveNews/squirrel-news-app#170]
@constructive-news We need to check the URL

**Comment by constructive-news** [comment]
Also das hier ist die richtige URL: ***@***.***_de 



—
Jonathan Widder

Vorstand
Constructive News e.V.

+49 151 1077 4782
***@***.***

constructive-news.org <https://constructive-news.org/>
squirrel-news.de <https://squirrel-news.net/de/>
—
Der Constructive News e.V. ist ein gemeinnütziger Verein mit Sitz in Berlin. 
Er ist im Vereinsregister des Amtsgerichts Charlottenburg unter dem Aktenzeichen VR 37904 B eingetragen.

**Comment by olierxleben** [comment]
not reproduceable
