### ISSUE TITLE
Burger Menu [Dev-2.0]

### ISSUE THREAD

**Issue by hstaatsxx** [ConstructiveNews/squirrel-news-app#23]
User story:
**As a** Developer
**I want** to integrate existing and new menu items in a sidebar/burger menu
**So that** our code and design is better compatible with the framework we are using

Acceptance criteria:
_Given_ the user is in the App
_When_ he clicks on a burger menu icon in the upper right corner
_Then_ a list of menu items appears

Dependencies:
none

Description:
We're replacing the navigation bar on the bottom and replacing it with a burger menu that will appear in the upper right corner as this works better with Ionic

DoD Checklist:
- [ ] Acceptance criteria are met
- [ ] Test by developer has been done
- [ ] Code is commented if required
- [ ] Code/PR review has been done
- [ ] Feature is documented
- [ ] Internal test by a 2nd Dev or the PO has been done

**Comment by hstaatsxx** [comment]
The burger menu using Ion was partly already implemented but without proper function.
Implemented in this issue scope are:
- SideMenu.tsx under components folder which will be called inside of BaseLayout.tsx.
- Burger menu with overlay style
- Menu items (see also issue #24)
- Podcast verlinkung (see issue #25)

During the implementation found out:

- Inside of IonPage Component each component should have different top-padding 
(ex. Teaser page full hight with image, others with top-padding with hight of Top menu bar)



![Image](https://user-images.githubusercontent.com/31039939/201916231-d37be7ae-5eae-4c2a-8816-6d0ed7fec8b9.png)
![Image](https://user-images.githubusercontent.com/31039939/201916232-b4717998-c753-4f29-bc2d-f97683c2c451.png)


This could be handled in a new issue.

**Comment by DevJacobi** [comment]
Testing was documented in the PR [here](https://github.com/ConstructiveNews/squirrel-news-app/pull/25#issuecomment-1338103703)

**Comment by hstaatsxx** [comment]
Here is the documentation for the feature (as discussed in https://github.com/ConstructiveNews/squirrel-news-app/issues/46).

### Documentation
**Short description of the change**
Implemented burger menu with Ionic Menu feature.
The basic format was already given. Menu items are added. 
Pages without top padding were overlapping with the burger menu item -> CSS updated.

**Codebase Changes**
SideMenu.tsx is added under the components. In this component, the Page interface works as one menu item.
Code is written for generic use, extension for further menu items should be easily done.
Base Layout is with the further paths configured.


**Visual Documentation**
Video from test in PR

https://user-images.githubusercontent.com/31039939/208980590-9adf483f-140d-47bf-9a99-9445e83eff30.mp4
