### ISSUE TITLE
Burger Menu - Items [Dev-3.0]

### ISSUE THREAD

**Issue by hstaatsxx** [ConstructiveNews/squirrel-news-app#24]
User story:
**As a** User
**I want** to find the existing menu items of the 3-dot menu in a the burger menu
**So that** I can use the apps features

Acceptance criteria:
_Given_ the user opened the burger menu
_When_ a user clicks on one of the items
_Then_ the corresponding page opens

Dependencies:
Burger Menu [Dev-2.0]

DoD Checklist:
- [ ] Acceptance criteria are met
- [ ] Test by developer has been done
- [ ] Code is commented if required
- [ ] Code/PR review has been done
- [ ] Feature is documented
- [ ] Internal test by a 2nd Dev or the PO has been done

**Comment by hstaatsxx** [comment]
Menu items added:

- Home
- Archive
- Favorite
- Donation
- Podcast (external link open - related to #22 )
- About
- Imprint
- Privacy Policy

**Comment by hstaatsxx** [comment]
More menu items should be added such as Current Issue (show Teaser Page maybe)

**Comment by DevJacobi** [comment]
Testing was done in the PR [here](https://github.com/ConstructiveNews/squirrel-news-app/pull/25#issuecomment-1338103703)

**Comment by hstaatsxx** [comment]
Here is the documentation for the feature (as discussed in https://github.com/ConstructiveNews/squirrel-news-app/issues/46).

Documentation added in #23
