### ISSUE TITLE
Podcast episode list [Dev-13.0]

### ISSUE THREAD

**Issue by hstaatsxx** [ConstructiveNews/squirrel-news-app#33]
User story:
**As an** editor 
**I want** the SN podcast episodes to be displayed in a list
**So that** users can browse episodes in their language inside the app

Acceptance criteria:
_Given_ the burger menu is opened
_When_ the user clicks the podcast menu item
_Then_ a new view opens up

_Given_ the podcast list view is shown
_When_ podcast episodes are released
_Then_ each episode is displayed as a single list item

_Given_ the podcast list view is shown
_When_ the user scrolls through the list
_Then_ episodes are ordered descending by episode number

_Given_ the podcast list view is shown
_When_ a podcast list item is displayed
_Then_ the item contains the image, title, publication date, creator(s)

_Given_ the podcast list view is shown
_When_ a user clicks on an episode item
_Then_ the webpage of that podcast episode is opened

_Given_ the app is set to en
_When_ the podcast list view is opened
_Then_ the episodes of the English SN podcast are shown

_Given_ the app is set to de
_When_ the podcast list view is opened
_Then_ the episodes of the German SN podcast are shown

Dependencies:
none

DoD Checklist:
- [x] Acceptance criteria are met
- [x] Test by developer has been done
- [ ] Code is commented if required
- [ ] Code/PR review has been done
- [ ] Feature is documented
- [ ] Internal test by a 2nd Dev or the PO has been done

**Comment by hstaatsxx** [comment]
Podcast information will be fetched from the rss url "https://podcast.squirrel-news.net/deutsch.rss".
I will first work on the german version.

Approx. approach:
Writing rss reader to read each item from rss
Generate PodcastItem from Item
Add a podcast list view same as the archive and favorites list.

**Comment by hstaatsxx** [comment]
![Image](https://user-images.githubusercontent.com/31039939/204353595-bd82c646-46ed-4fd6-b56d-b6d08b6dedd7.png)

First draft with the given german RSS feed.
There are no image sources in the RSS feed for the same image that is displayed as each episode-related image on the website.
Only Podcast Logo.

This will be selected for now. 
For the SN feedback uploaded in slack channel.

**Comment by DevJacobi** [comment]
Tested it and linked the test in the PR [here](https://github.com/ConstructiveNews/squirrel-news-app/pull/35#issuecomment-1338075878)

**Comment by DevJacobi** [comment]
A minor remark: I think it is my internet connection but when I clicked in the menu to load the podcast list, I needed to wait a bit to get everything loaded. Could someone verify that this is just my internet connection? @hstaatsxx @DavidKeanu

**Comment by grollk** [comment]
Requirement will be addressed in Ticket _Überschriften in den Sub-Menüs [Dev-18.0]_

**Comment by hstaatsxx** [comment]
<img width="375" alt="Bildschirmfoto 2022-12-13 um 12 37 42" src="https://user-images.githubusercontent.com/31039939/207308345-14706c99-73f0-478e-8904-d029ce2d42da.png">

**Comment by hstaatsxx** [comment]
Here is the documentation for the feature (as discussed in https://github.com/ConstructiveNews/squirrel-news-app/issues/46).

### Documentation
**Short description of the change**
Podcast menu used to be a simple forwarding link to the podcast page on the web app.
In this issue, a proper episode list page is created which displays all podcast episode lists with given image and headline.
Information about podcasts was retrieved from the RSS file.

**Codebase Changes**
Generated PodcastPage.tsx -> Iteration all episodes and add as a list item.
Update in SideMenu with the /podcast path.

**Visual Documentation**
already uploaded in the previous comment
