### ISSUE TITLE
Scroll and Swipe Navigation - Research [Dev-9.0]

### ISSUE THREAD

**Issue by DavidKeanu** [ConstructiveNews/squirrel-news-app#34]
User story:
**As a** PO/Dev
**I want** to know what the best practices regarding scrolling navigation are
**So that** I can make an informed decision when choosing an implementation

Acceptance criteria:
- one ore more possible solutions are documented
- suggested solutions are based on best practices

Dependencies:
none

**Comment by DavidKeanu** [comment]
Update: Eine Lösung sind Ionic gestures: https://ionicframework.com/docs/utilities/gestures

**Comment by hstaatsxx** [comment]
Ionic gestures seem like it is more adding specific action for a specific gesture, such as double-click than that should happen.

We could consider implementing Swiper React Component in the app.
It has not only swipe but also vertical swipe (which means scroll in our case)

Codesandbox example for vertical swipe.
https://codesandbox.io/s/62rdbz?file=/src/App.jsx

**Comment by DevJacobi** [comment]
Update after review: Oliver pointed out we should research about the licence for the used library

**Comment by grollk** [comment]
@DevJacobi swiper.js is licensed under MIT, and included in ionic, therefore we are able to use it

**Comment by pfkeen** [comment]
@hstaatsxx & @DavidKeanu i just talked to @DevJacobi and we were wondering if this one is finished? If yes, please update status and wirte a final comment. Thanks. :)

**Comment by hstaatsxx** [comment]
Research is done. Implementing will be done in #44 .
