### ISSUE TITLE
CI-Pipeline GitHub Actions PR Android [DevOps-3.0]

### ISSUE THREAD

**Issue by Fatihevliyaoglu** [ConstructiveNews/squirrel-news-app#39]
- PR opened should build artifact from feature-branch automatically
- hand over to OE review the ticket
- ticket reviewed from OE and finalized

**Comment by Fatihevliyaoglu** [comment]
- hand over ti review the ticket

**Comment by Fatihevliyaoglu** [comment]
- ticket reviewed from OE and finalized

**Comment by 12tobi3** [comment]
OE wants to provide a test environment for us that we are still waiting for.

**Comment by 12tobi3** [comment]
Tested GitHub Actions in a demo project.

**Comment by Fatihevliyaoglu** [comment]
- Bitrise Accounts were created for the DevOps from OE 
- Webhook setup with OE and DevOps

**Comment by Fatihevliyaoglu** [comment]
- PR opens build and artifact from feature-branch are automatically created
- just correct path is missing

**Comment by Fatihevliyaoglu** [comment]
- google.service.json file was added 
- need to modify the secret-keys

**Comment by 12tobi3** [comment]
-fixed google-service.json file 
- added secrets
- added necessary dependencies
