### ISSUE TITLE
CI-Pipeline GitHub Actions merge Android [DevOps-4.0]

### ISSUE THREAD

**Issue by Fatihevliyaoglu** [ConstructiveNews/squirrel-news-app#40]
- PR Merged should build artifact form main-branch automatically
- hand over to review from OE
- ticket reviewed from OE and finalized

**Comment by Fatihevliyaoglu** [comment]
- hand over to review from OE

**Comment by Fatihevliyaoglu** [comment]
- ticket reviewed from OE and finalized

**Comment by 12tobi3** [comment]
OE wants to provide a test environment for us that we are still waiting for.

**Comment by Fatihevliyaoglu** [comment]
- Bitrise Accounts were created for the DevOps from OE 
- Webhook setup with OE and DevOps

**Comment by Fatihevliyaoglu** [comment]
- the ticket was taken to the new sprint

**Comment by Fatihevliyaoglu** [comment]
- build and artifact from feature-branch are automatically created

**Comment by Fatihevliyaoglu** [comment]
- google.service.json file was added
- need to modify the secret-keys

**Comment by 12tobi3** [comment]
- fixed google-service.json file 
- added secrets
- added necessary dependencies
