### ISSUE TITLE
Complete text variables (EN/DE) [Dev-14.0]

### ISSUE THREAD

**Issue by DavidKeanu** [ConstructiveNews/squirrel-news-app#43]
User story:

**As a** user
**I want** texts and their translations to be improved
**So that** i have a better experience using the app

Acceptance criteria:
_Given_ the app is opened
_When_ the user navigates the app
_Then_ the updated texts are displayed

> Alle Ausgaben - All issues
> Favoriten - Favourites
> Unterstützen - Support us
> Impressum - Legal notice

Dependencies:
none

DoD Checklist:
- [x] Acceptance criteria are met
- [x] Test by developer has been done
- [x] Code is commented if required
- [x] Code/PR review has been done
- [ ] Feature is documented
- [x] Internal test by a 2nd Dev or the PO has been done

**Comment by DavidKeanu** [comment]
Update: 
added translation for the sidemenu. Check images for improvements.
 

![Image](https://user-images.githubusercontent.com/58940306/207685197-65544016-8e0a-49da-b112-e8b7f3bf1a59.png)
![Image](https://user-images.githubusercontent.com/58940306/207685198-da8c9b06-852e-4fae-a7c8-1776c876d162.png)
![Image](https://user-images.githubusercontent.com/58940306/207685199-1892014b-9880-4533-8093-6ff7d4ac8323.png)

**Comment by grollk** [comment]
@DavidKeanu please change the menu item "Archiv" - "Archive" to "Alle Ausgaben" - "All issues", to meet the acceptance criteria

**Comment by DavidKeanu** [comment]
Update: Changed menu items according to @grollk comment.

**Comment by DevJacobi** [comment]
@DavidKeanu why did you unassign yourself and assigned @hstaatsxx and me? Did you want to create a PR and assign @hstaatsxx and me?

**Comment by DavidKeanu** [comment]
Here is documentation for the feature (as discussed in https://github.com/ConstructiveNews/squirrel-news-app/issues/46).

Documentation
Short description of the change

Change of text variables for alles pages.

Codebase Changes

Text changes in lanugages.ts
