### ISSUE TITLE
Language Selection Setting [Dev-17.0]

### ISSUE THREAD

**Issue by grollk** [ConstructiveNews/squirrel-news-app#45]
User story:
**As a** User
**I want** the language setting reworked
**So that** it better fits in the new settings page

Acceptance criteria:
_Given_ the settings page is open
_When_ a language is chosen from a selection box
_Then_ the issue language gets changed

Dependencies:
Darkmode - Toggle [Dev-8.0]

DoD Checklist:
- [x] Acceptance criteria are met
- [x] Test by developer has been done
- [x] Code is commented if required
- [ ] Code/PR review has been done
- [ ] Feature is documented
- [ ] Internal test by a 2nd Dev or the PO has been done

**Comment by DavidKeanu** [comment]
Update: In progress.

**Comment by DevJacobi** [comment]
As discussed in the review with Oli and Jonathan, we want to change "Deutsche Ausgabe, Englische Ausgabe", "German Edition, English Edition" to just the language: "German, English", "Deutsch, Englisch".
@grollk can you create an issue for this small refactoring?

**Comment by DavidKeanu** [comment]
Here is documentation for the feature (as discussed in https://github.com/ConstructiveNews/squirrel-news-app/issues/46).

Documentation
Add selection box which triggers a language change selection.

Codebase Changes

mostly changes is language.ts
