### ISSUE TITLE
Content type tag im article teaser [Dev-19.0]

### ISSUE THREAD

**Issue by grollk** [ConstructiveNews/squirrel-news-app#56]
User story:
**As a** user 
**I want** to know the type of content for each article
**So that** i know what to expect before opening the article

Acceptance criteria:
_Given_ the an article teaser is shown
_When_ content types are delivered in the data model
_Then_ content type icons are shown

_Given_ the an article teaser is shown
_When_ no content types are delivered in the data model
_Then_ no content type icons are shown

_Given_ the an article teaser is shown
_When_ multiple content types are delivered in the data model
_Then_ multiple content type icons are shown

Dependencies:
[[Dev-20.0]](https://github.com/ConstructiveNews/squirrel-news-firebase/issues/2)
#29 

Reference:
Data Model
![image](https://user-images.githubusercontent.com/44089084/211004970-ca9dbe74-ea5d-4ffa-8a5d-839817f99312.png)

Mock up (for full reference and icons see figma)
<img width="186" alt="image" src="https://user-images.githubusercontent.com/44089084/211004831-0cd51825-e195-464b-a685-a3f027f1d07c.png">

DoD Checklist:
- [ ] Acceptance criteria are met
- [ ] Test by developer has been done
- [ ] Code is commented if required
- [ ] Code/PR review has been done
- [ ] Feature is documented
- [ ] Internal test by a 2nd Dev or the PO has been done

**Comment by DavidKeanu** [comment]
Update: Wartet auf https://github.com/ConstructiveNews/squirrel-news-firebase/issues/2

**Comment by olierxleben** [comment]
Hi, I added the possibility but did not migrate all articles.

**Comment by DavidKeanu** [comment]
Updatet: Implemented pov version for content type icons. Local testings was working. Waiting for "real" data from firbebase to test.

**Comment by DavidKeanu** [comment]
Here is documentation for the feature (as discussed in https://github.com/ConstructiveNews/squirrel-news-app/issues/46).

Documentation
Short description of the change

A content tag has been added. 
An icon is displayed depending on the type of article. 
There are icons items, audio and video. 
Codebase Changes
add content array field in issue data model.
add function in ArticleTeaser.tsx for conditionel rendering
add icons for different content types
Visual Documentation
![image](https://user-images.githubusercontent.com/58940306/216277195-c47f3fda-0332-4ae3-b9bf-e3c902a9bce2.png)

**Comment by olierxleben** [comment]
In my opinion this issue was solved. @constructive-news
