### ISSUE TITLE
Navigation Toggle [Dev-22.0]

### ISSUE THREAD

**Issue by grollk** [ConstructiveNews/squirrel-news-app#57]
User story:
**As a** user
**I want** to choose between scroll and swipe navigation
**So that** I can navigate the app according to my preferences

Acceptance criteria:
_Given_ the settings menu is opened
_When_ the settings items are displayed
_Then_ there is a toggle switch for the navigation style

_Given_ the toggle is clicked
_Then_ the navigation mode switches

_Given_ the toggle is set to scroll
_Then_ scroll navigation is used

_Given_ the toggle is set to swipe
_Then_ swipe navigation is used

Dependencies:
none

DoD Checklist:
- [x] Acceptance criteria are met
- [x] Test by developer has been done
- [x] Code is commented if required
- [x] Code/PR review has been done
- [x] Feature is documented
- [x] Internal test by a 2nd Dev or the PO has been done

**Comment by hstaatsxx** [comment]
Issue closed. Documentation is in #44
