### ISSUE TITLE
Überarbeitung Podcast Seite [Dev-24.0]

### ISSUE THREAD

**Issue by grollk** [ConstructiveNews/squirrel-news-app#58]
User story:
**As a** user
**I want** some spacing between podcast episodes in the list view
**So that** the view feels less cluttered 

Acceptance criteria:
_Given_ the podcast episode list view is opened
_When_ podcast episodes are loaded
_Then_ spacing and texts are in accordance to the mock up

Reference:
_For full Mock up with pixel values see figma_
![Image](https://user-images.githubusercontent.com/44089084/211003366-b32d1c44-d21f-46a3-b051-ab190ca82ba5.png)

Dependencies:
none

DoD Checklist:
- [x] Acceptance criteria are met
- [x] Test by developer has been done
- [x] Code is commented if required
- [ ] Code/PR review has been done
- [ ] Feature is documented
- [ ] Internal test by a 2nd Dev or the PO has been done

**Comment by DevJacobi** [comment]
### Documentation

**Short description of the change**
The podcast site was updated according to the mockup. 

**Codebase Changes**
This was visually only. Therefore the most changes were css.

**Visual Documentation**
![grafik](https://user-images.githubusercontent.com/43578928/214602326-9562f981-e2a8-4b20-8e0d-6d682ac60d42.png)
