### ISSUE TITLE
Überschriften auf den Seiten (Einstellungen/Podcast/etc.) [Dev-18.0]

### ISSUE THREAD

**Issue by grollk** [ConstructiveNews/squirrel-news-app#64]
User story:
**As a** user
**I want** to know which menu item I entered
**So that** I find my way around the app better

Acceptance criteria:
_Given_ the burger menu is opened
_When_ a burger menu item is clicked
_Then_ the title of the menu item is displayed at the top of the page view

Example:
Current Production Version for reference

![Image](https://user-images.githubusercontent.com/44089084/212281004-bc89893c-142f-4ffe-9b25-06ee5c033061.png)

Dependencies:
none

DoD Checklist:
- [ ] Acceptance criteria are met
- [ ] Test by developer has been done
- [ ] Code is commented if required
- [ ] Code/PR review has been done
- [ ] Feature is documented
- [ ] Internal test by a 2nd Dev or the PO has been done

**Comment by DavidKeanu** [comment]
Update: Added heading for pages with en/de translation. 
@constructive-news 


![Image](https://user-images.githubusercontent.com/58940306/212989944-b5fa097b-ebff-490b-a50a-9b977d374f00.png)

**Comment by DavidKeanu** [comment]
## Documentation
### Short description of the change
Added headers for subpages
### Codebase Changes
changes in all subpages.

### Visual Documentation
![image](https://user-images.githubusercontent.com/58940306/217936206-21c41c21-dd71-4b33-8fa3-62349b687b7d.png)
