### ISSUE TITLE
Bugfix system share dialog api call [Dev-32.0]

### ISSUE THREAD

**Issue by grollk** [ConstructiveNews/squirrel-news-app#75]

**Comment by hstaatsxx** [comment]
Thank you @olierxleben  for testing!
Oli sent me all testing pics for both android and ios.
<img width="603" alt="image (1)" src="https://user-images.githubusercontent.com/31039939/216171334-07bbf3e9-998e-4785-9d8c-9c80b2f8335a.png">
<img width="559" alt="image (2)" src="https://user-images.githubusercontent.com/31039939/216171344-7403b8bb-0234-4a27-abca-52e0a36598b1.png">

Share dialog works fine in both.
