### ISSUE TITLE
Recommend App Button - MVP [Dev-28.0]

### ISSUE THREAD

**Issue by grollk** [ConstructiveNews/squirrel-news-app#76]
User story:
**As a** user
**I want** a quick and familiar way to share the app
**So that** I can share it with other people

Acceptance criteria:
_Given_ the issue is shown
_When_ the user reaches the 'more-page'
_Then_ the share app function is located below 'favourites' as clickable text

_Given_ the share app button shown
_When_ the user clicks it
_Then_ a system share dialog is displayed (like the share article feature)

_Given_ the system dialog is displayed
_When_ an app for sharing is clicked
_Then_ a text from the firebase backend is copied to the respective app

_Given_ the share app feature is used
_Then_ the preset text and link to SN are localized according to the set issue

Dependencies:
- #75
- https://github.com/ConstructiveNews/squirrel-news-firebase/issues/3

DoD Checklist:
- [ ] Acceptance criteria are met
- [ ] Test by developer has been done
- [ ] Code is commented if required
- [ ] Code/PR review has been done
- [ ] Feature is documented
- [ ] Internal test by a 2nd Dev or the PO has been done

**Comment by hstaatsxx** [comment]
We got the link from firebase. Final implementation is still open.

**Comment by hstaatsxx** [comment]
Implementation for Recommend App Button is done, but the share dialog is still not properly displaying.
However, it will be fixed in ticket #75. So this issue will be closed for now. If additional correction is needed, there will come another bug-fix ticket.

**Comment by hstaatsxx** [comment]
## Documentation
### Short description of the change

The implementation of this issue enables share dialog just like from the article teaser for recommending the app.
Recommending text and sharing links come from firebase and it was implemented in #79.

## Codebase Changes
The "handleShare" function is copied from the ArticleTeaser page and added to MorePage. The recommend related data from the firebase will be called inside of the useEffect function.

## Visual Doc
<img width="603" alt="image (1)" src="https://user-images.githubusercontent.com/31039939/216539659-3cea9b4c-5e12-4f8f-b190-917a3a28a4b5.png">
<img width="559" alt="image (2)" src="https://user-images.githubusercontent.com/31039939/216539662-1cd367af-40ba-4c83-9714-e1d8c3332aa8.png">

Tested by @olierxleben
