### ISSUE TITLE
Archive Page has no way (no UI) to load more data than the first chunksize

### ISSUE THREAD

**Issue by olierxleben** [ConstructiveNews/squirrel-news-app#99]
If we navigate to the archive, we currently get the 10 latest issues. There is no way to provide older archives.

To make it Ready we need: 

- [ ] UI / UX Design to implement a solution
- [ ] Acceptance Criteria

**Comment by olierxleben** [comment]
Needs refinement and design work @constructive-news

**Comment by constructive-news** [comment]
Can't we just do it as we currently do it in Alle Ausgaben (in the Angular app)?
